### ISSUE TITLE
Позаимствовать/придумать модельный квест

### ISSUE THREAD

**Issue by mariohuq** [RodosTeam/QuestTime#4]
Здесь имеется ввиду именно контент, а не его представление в файлах или коде.

Результат по этой задаче — документ/блок-схема с картинками (опционально), где неформально описаны состояния и переходы, где переход это один или несколько текстовых блоков с (возможно меняющимися картинками).

Это если что-то похожее на визуальную новеллу.

Лучше ограничить размер 2-4 концовками, и выбор - 1-3 вариантами.

**Comment by Alexandra-Tkachenko** [comment]
[Twine](https://twinery.org) - наиболее подходящий под задачу движок, в таком случае. Из альтернатив -  Квестер, AXMA и Аперо, но функционал, в целом, похож.
Для самого сюжета можно посмотреть [AI Dungeon](https://play.aidungeon.io/main/home)
